name: 定时执行脚本

on:
  schedule:
    - cron: '0 0 * * *'  # 每天的 UTC 时间 0 点执行（北京时间上午 8 点）
  workflow_dispatch:  # 允许手动触发

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 根据你的需求选择 Python 版本
      - run: pip install -r requirements.txt  # 安装依赖（如果有）
      - run: python your_script.py  # 替换为你的脚本路径
